### ISSUE TITLE
Review count font is Times Roman should be roboto

### ISSUE THREAD

**Issue by happivize** [happivize/live#10]
I noticed the review count is not our default font. Can you change to roboto

![image](https://user-images.githubusercontent.com/28787692/33799582-92c10bce-dcfc-11e7-92f3-b058e13cea43.png)

**Comment by shpp-shablyuk** [comment]
Done.
http://i.prntscr.com/mKDYpXaqTFCCQozuBkv3HA.png
`
.woocommerce-product-rating .star-rating,
.price-wrapper .star-rating {
    width: 6.3em;
}

.woocommerce_get_star_rating_count {
    margin-left: 2px;
    color: #000;
    position: absolute;
    left: 80px;
    font-size: 15px;
    font-family: Roboto, sans-serif;
}
`

**Comment by happivize** [comment]
thanks, i just added this, but i changed the width to 6.7em because it was
cutting off the number and right parentheses if it was double digit, i also
changed the font-size to 13
