### ISSUE TITLE
Contents displayed on cart and receipt

### ISSUE THREAD

**Issue by happivize** [happivize/live#11]
So right now we use Product Short Description field in Products to list the bullets under the Title of the Product.

I would like another text field added to Product page where I can list the items included like:

- 12 MP3s
- 3 Live Group Calls
- One Private Session

These would be bulleted and display under the product in cart/checkout and also on the email receipt. 

I believe this was the original functionality of Product Short Description. But we already have a lot of that populated with the pink star bullets to display on the Single Product Page, so we just can't turn that functionality back as they are different sets of bullets.

What do you advise we do?

**Comment by shpp-shablyuk** [comment]
I can add to the admin part of the product page an additional field using the AСF plugin. And then display it in the cart/checkout and email receipt

**Comment by happivize** [comment]
OK, please proceed. For formatting, I want the description bullets to

a) have hanging indent for each bullet, so the second line of text is lined up under the first line of text, not under the bullet
b) be a slightly smaller font than the Product Name so if Product Name is 12pt then Description would be 10pt
c) be a slightly lighter color so if Product Name is black, then Description should be a dark grey

**Comment by shpp-shablyuk** [comment]
I made a test version, but in emails its shown without the bullets for now. Check how it works for the cart and checkout, please

**Comment by happivize** [comment]
On dev I can't find a new admin field where I would add the contents so
that I can test it.

**Comment by shpp-shablyuk** [comment]
https://prnt.sc/hqng3a

**Comment by happivize** [comment]
Oh you put it up above, I never look at anything up above the product data
box because we always have to skip over that big text field as we don't use
it for anything.

1) Please move it below. Actually, can you make it a tab on the Product
Item box

[image: Inline image 1]

2) Please have a visual and a text tab for the field (we paste things and
it's easier to paste into text, but we also need a visual)

3) Right now it's using the pink bullet starts - I just want regular
bullets.

4) It's also indenting each bullet further and further, they should all be
left aligned. Hanging Indent is so that the second line of one bullet is
lined up under the text of the first line of the bullet when it wraps to a
second line, not that the 2nd bullet is lined up under the text of the
first bullet. That's for cart, checkout, thank you page, and email.

5) The email as you said doesn't have the bullets, it should just a regular
single bullet, also it has the first one indented quite far, it should be
left aligned like the item name

**Comment by shpp-shablyuk** [comment]
I don't see the attached image. Can you repeat what tab on the Product Item box should look?

> 1) Please move it below. Actually, can you make it a tab on the Product
Item box

>[image: Inline image 1]

**Comment by shpp-shablyuk** [comment]
I fixed the bullets and indents

Here is the tab location https://prnt.sc/hr1fjf

**Comment by happivize** [comment]
1. Can you rename the tab to Contents
2. I dont' see #2 addressed, I only see visual, not a text

**Comment by shpp-shablyuk** [comment]
done

**Comment by happivize** [comment]
thanks looks good. What do I need to move to live?

**Comment by shpp-shablyuk** [comment]
snippet: https://prnt.sc/hskw7p
Styles for "flatsome-child/style.css" 
[style.txt](https://github.com/happivize/live/files/1587790/style.txt)

**Comment by happivize** [comment]
Thanks this is working on live now, looks great.

**Comment by happivize** [comment]
This is not allowing me to change the contents of the tab once saved. I have cleared cache, purged cache, and tried to update the contents but keeps reverting back to original. Here is video:

https://www.screencast.com/t/CKSXN3vmR

This is the product I was editing
https://happivize.com/wp-admin/post.php?post=42347&action=edit

**Comment by happivize** [comment]
Also, I cloned the product in case it was corrupted and tried to update, same problem

**Comment by happivize** [comment]
PS I started new and now it won't save anything - it's just blank. I add in the content and update and it disappears. May have something to do with its being a subscription product?

**Comment by shpp-shablyuk** [comment]
I'll look for the cause of the problem

**Comment by shpp-shablyuk** [comment]
Check please
https://dev.happivize.com/wp-admin/post.php?post=42347&action=edit

If this works fine, you should update the snippet

**Comment by happivize** [comment]
OK I was able to update it on dev, although I hadn't tested it on dev to
make sure it also wasn't working there.

But I'll copy the dev snippet over to live and test.

**Comment by happivize** [comment]
OK snippet updated and it works on live now.
