### ISSUE TITLE
Image won't center / Create Float Left with margin CSS Class

### ISSUE THREAD

**Issue by happivize** [happivize/live#12]
Hi can you take a look at this page. The top image I cannot center.

http://dev.happivize.com/iehcarollook/

I had to update your password to this because I had a fresh copy of live put on dev so your old password probalby doesn't work

https://quickforget.com/s/77bb77a0b79d04ae600f34338d7ce27b

**Comment by shpp-shablyuk** [comment]
Changes here:
https://prnt.sc/hy4bni
https://prnt.sc/hy4c40
https://prnt.sc/hy4ca8

**Comment by happivize** [comment]
I don't understand this. You added this CSS on storefront theme? That's
what I see on the first screen that Storefront is Active but as you know I
use flatsome.

Also, I can't have CSS that changes everything for every image...so I'm
confused on what you did, what was causing the problem in the first place?

**Comment by shpp-shablyuk** [comment]
When I visited your website, the Storefront theme was activated. So I made changes in the active theme. 

The problem is that in the theme the CSS rules for the "img"  tag are changed. For the visual editor Elementor, I set the default value for the  "img"  tag via Customizer (Customize menu). In the screenshots I showed where to find these changes in the Customizer

**Comment by happivize** [comment]
I have people testing the subscription problem on the dev site, so they may have changed it to storefront for testing. Can you take a new local copy and use our normal Flatsome Child theme.

And then tell me where the changes need to be made? because making them in storefront won't help.

I need to also know specifically what and where the CSS that changed it for that page was. Because I can center on other pages.

**Comment by shpp-shablyuk** [comment]
In the page editor, I set the image alignment centered and now the image is centered. Does this work for you now, too?
https://prnt.sc/hy5rg4

**Comment by happivize** [comment]
well it's not so much that i want that one image to work i want to know what was causing the conflict that it wasn't working directly - do you know the root cause

**Comment by happivize** [comment]
Also, the whole time that centered formatting was selected, i tried all of the alignment formats and nothing changed. so there was some other CSS causing it. it does seem to be working now. But i want to know what fixed it

**Comment by shpp-shablyuk** [comment]
I haven’t yet made any changes for the Flatsome Child theme. I just see that in the editor of this page the image centering is now working. 
Are there more pages where there is a similar problem?
If so, give me a links to them.

**Comment by happivize** [comment]
what happens if you undo what you did to storefront theme, does it work then?

**Comment by shpp-shablyuk** [comment]
Yes, it works.

**Comment by happivize** [comment]
ok, that is so strange as it hasn't been working for a week, i don't know what makes it work now, when essentially you haven't done anything.

But now the image at the bottom doesn't look correct, the text is right up against the edge.  

Can you create a css class that when applied to a specific image it will float left and have a margin of 10 px on the right and bottom?

**Comment by shpp-shablyuk** [comment]
`
.img-float-left-with-padding {
  float: left;
  padding: 0 10px 10px 0;
}

`

**Comment by happivize** [comment]
if i add that to Custom CSS it will affect all images in elementor, not just the one image. i need to have a specific class that I can add to one image. I tried applying class img-float-left-with-padding

but that didn't change anything.

**Comment by happivize** [comment]
![image](https://user-images.githubusercontent.com/28787692/34739628-e24742a6-f54a-11e7-8ae0-a6a14aee3d60.png)

See the CSS classes on the left, if i add it to custom css below, then it affects all images

**Comment by happivize** [comment]
i guess what i'd like is to be able to type something like float-image-left for the CSS class for that image or any image i want to float like that and it does it

**Comment by shpp-shablyuk** [comment]
You should add css-class here
https://prnt.sc/hy70jv

**Comment by happivize** [comment]
i would prefer to add the class to that other place, because it's much cleaner to add it there for those of us who don't code. is it possible to add it there?

**Comment by shpp-shablyuk** [comment]
done

**Comment by happivize** [comment]
i can't get it to work, can you send me screenshots of showing it working?

**Comment by shpp-shablyuk** [comment]
Renamed class to "float-image-left"

https://prnt.sc/hy7g02

**Comment by happivize** [comment]
ok, it was a cache problem, it is working now - so i can use that class for any image on any page to float left with padding, correct?

how would I do it here:
https://dev.happivize.com/product/success-and-spirit-2/#tab-about-mia-den-haan

That is a custom tab in the product

**Comment by shpp-shablyuk** [comment]
> how would I do it here:
https://dev.happivize.com/product/success-and-spirit-2/#tab-about-mia-den-haan

Like here
https://prnt.sc/hy8jje

**Comment by happivize** [comment]
Great thanks. I will close this issue. We can use this class for adding the Seller Info in WC Vendor once that is worked out.

**Comment by happivize** [comment]
Oops I just realized this is onl on dev, can you give me instructions to add it to live?

**Comment by shpp-shablyuk** [comment]
add this styles to flatsome-child/style.css

`
/* image floating */
.float-image-left img {
    float: left;
    padding: 0 10px 10px 0;
}

img.float-image-left {
    float: left;
    padding: 0 10px 10px 0;
}
/* end image floating */
`

**Comment by happivize** [comment]
Thanks have added to live and tested, this is working
