### ISSUE TITLE
Free snippet making some Grouped Products Free

### ISSUE THREAD

**Issue by happivize** [happivize/live#15]
I added the snippet Product: Make Free if price is $0 from this page

https://github.com/woocommerce/woocommerce/issues/13658

It works on simple products like it's supposed to, but on SOME grouped products it also displays free even though there is no free product associated with it. Some grouped products works fine

https://github.com/woocommerce/woocommerce/issues/13658

1) Works correctly here on this free interview product

2) Group product correct here does not show free

3) Group product wrong here, shows it as free on the shop page

Can you figure out why it's not 100% working?

**Comment by shpp-shablyuk** [comment]
Check please.

**Comment by happivize** [comment]
Yes this work, I updated the snippet on live with your edits from dev.
