### ISSUE TITLE
Change width of Search bar on computer

### ISSUE THREAD

**Issue by happivize** [happivize/live#16]
The Search bar is too small on the laptop see image here. Can you make it twice as wide so that it's easy to read the results?  I tried to do it on Flatsome theme but it was like it interfered with the other block in the bar to the left.

On mobile it looks good (width of mobile).

![image](https://user-images.githubusercontent.com/28787692/36163507-98273568-10b7-11e8-9885-89067fa44b75.png)

**Comment by shpp-shablyuk** [comment]
https://dev.happivize.com/

Check please.

**Comment by happivize** [comment]
Looks good. It actually changed it on my tablet too, but it looks better so
I'll keep it. How do I add to live?

**Comment by shpp-shablyuk** [comment]
https://prnt.sc/iea7gc

**Comment by happivize** [comment]
has been working for almost a month now
