### ISSUE TITLE
Subscription Description when includes free trial and synchronization

### ISSUE THREAD

**Issue by happivize** [happivize/live#17]
I had my other programmer Aleksandr change what comes after the subscription price for a couple of products. You can see the code in his upwork named file for php in child theme. It's around line 383. It changes it to say subscription begins in 30 days.

I need to have another option where it says First payment on April 27th, or whatever the first payment will be. You can see that the code is already on there, I need that to replace what it naturally puts.

![image](https://user-images.githubusercontent.com/28787692/36163698-2899838a-10b8-11e8-8f5e-79fb4576ccec.png)

Can you create similar code and make it a snippet where I just add the product number when I have another product I want to have similar formatting? Currently that's what I do in the upwork code (add a nother product number) but I would much prefer it be in snippet. 

I don't have this product in dev, but if you make a sub product that has 60 day free trial and is synchronised to bill on the 27th of the month, then you will have the same product to work with.

**Comment by shpp-shablyuk** [comment]
https://prnt.sc/iflizr

**Comment by shpp-shablyuk** [comment]
Also, I can add a checkbox to the product settings for adding description on the subscription

**Comment by happivize** [comment]
this has been working for awhile now
