### ISSUE TITLE
WC Vendor: Remove Sold By / Offered By everywhere

### ISSUE THREAD

**Issue by happivize** [happivize/live#3]
Right now on the Thank You page and the Completed Order (receipt sent to customer) it is auto added under product description to say Sold by: Vendor Name. (although I have edited it to say Offered By:)

I want that removed in all instances. There is a toggle for it in Settings for the plugin, and it removes it in Cart, but not these other places. The developers are aware of it, but I can't wait on them.

**Comment by happivize** [comment]
i placed a new order on a incognito window, it is still showing offered by on Completed Order email

https://www.screencast.com/t/PwVZjLa6aC5
![image](https://user-images.githubusercontent.com/28787692/33532697-d894dd66-d869-11e7-8c78-b3bb35cdaf06.png)

**Comment by shpp-shablyuk** [comment]
What products can I check for sending email?

**Comment by happivize** [comment]
I think they all have it.

**Comment by shpp-shablyuk** [comment]
Done. Check please.

**Comment by happivize** [comment]
moved to live via Snippet - tested and working

**Comment by happivize** [comment]
So I realized that now the the Thank You page /order-received/ no longer has the header that says something like Great your order has been processed and the Next Steps. These are super important so that the person knows what to do after ordering. This happened as a result of this change, so reopening

**Comment by happivize** [comment]
Here's what my latest receipt looks like versus the one I pasted in above with the Next Steps (for dev)

![image](https://user-images.githubusercontent.com/28787692/33696368-f48f077c-dacf-11e7-9b46-6e6335b4d4fc.png)

**Comment by shpp-shablyuk** [comment]
For the test product, I set this setting https://prnt.sc/hkgb6x. And now the Next steps are shown

**Comment by happivize** [comment]
working via snippet
