### ISSUE TITLE
Email Order Details to Customer not working

### ISSUE THREAD

**Issue by happivize** [happivize/live#6]
If I want to resend the Completed Order email I used to be able to open an order that has been placed, go to Order actions on the right and send Completed Order. With woo 3.2 they have changed the wording and now it is:

Email Order Details to Customer

![image](https://user-images.githubusercontent.com/28787692/33532739-45b5e2a0-d86a-11e7-804c-3e4a98316956.png)

BUT that is generating a payment invoice email, even though the order is completed.

![image](https://user-images.githubusercontent.com/28787692/33532751-63d839e0-d86a-11e7-88bc-929b445b3501.png)

I have emailed woo tech support and they said that should be sending Completed Order.

BTW, I have a plugin called something like WC Advanced Email Customization that I use to send out my emails, they have been customized a lot.

**Comment by shpp-shablyuk** [comment]
I added the action to send emails
https://prnt.sc/hk11tw
Does this solution suit you?

**Comment by happivize** [comment]
Yes that works, please reply with how to add it to live

**Comment by shpp-shablyuk** [comment]
https://prnt.sc/hk19kc

**Comment by happivize** [comment]
added to live via snippet, tested and closed
