### ISSUE TITLE
WC Vendor: Date of Sale not corresponding to system date

### ISSUE THREAD

**Issue by happivize** [happivize/live#7]
I have this on my live site too. I had a sale that was at 18:50 and it showed today, 12/4 on the Vendor site. But a sale at 19:13 showed to be on 12/5. All sales after 19h showed the next day when logged in as a vendor. I have my site set to New York time and everything but WC Vendor works off that WordPress Setting. I do not see anywhere to set the time for WC Vendor directly.

I would suggest creating a new user account with role vendor, and then assigning a product with you as vendor in the product backend, there is a new field box that says Vendor with a dropdown. Then you can see what the vendor would see at /vendor_dashboard

**Comment by happivize** [comment]
I tested with a purchase after 19h my time and it is the same result as before. Here is a video:

https://www.screencast.com/t/EFUShRqDV5

**Comment by shpp-shablyuk** [comment]
fixed

**Comment by happivize** [comment]
OK, will test after 19h tonight

**Comment by happivize** [comment]
Tested tonight, confirmed it is working. Please provide steps to add to live

**Comment by shpp-shablyuk** [comment]
This task is related to #8, so when I finish, I'll give you the snippet and the files common to these two tasks

**Comment by happivize** [comment]
also this does not appear to be working either, here is an order that was placed on 12/4 at 23:24 pm but it is showing on 12/5

![image](https://user-images.githubusercontent.com/28787692/33964746-7e91e74e-e027-11e7-8c83-afab702b48da.png)

**Comment by happivize** [comment]
combind with #8, added snippet and added WC Vendor files to Child Theme.
