### ISSUE TITLE
WC Vendor: Remove address details from what Vendor is given

### ISSUE THREAD

**Issue by happivize** [happivize/live#8]
Right now, the Vendor can see the billing address of the customer in two places, I don't want them to see or be able to download anywhere.

#1 
![image](https://user-images.githubusercontent.com/28787692/33696477-643fc2fa-dad0-11e7-800c-f354cc79dcf4.png)

#2 When you click "Show Orders" on the above screenshot for a product, you see this, please also remove the columns displayed there:

![image](https://user-images.githubusercontent.com/28787692/33696531-aa5fc186-dad0-11e7-8e9e-1767aa81d1b7.png)

**Comment by happivize** [comment]
Also when someone clicks Export Orders, they should also only be able to export the data displayed in the table

**Comment by shpp-shablyuk** [comment]
Should I delete the line with a comment? http://prntscr.com/hkgs1b

**Comment by happivize** [comment]
Actually I realized that is a setting for WC Vendor, I have disabled comments and it no longer shows, so no need to delete it.Can you move the Qty from being a row in the table to a column?

**Comment by shpp-shablyuk** [comment]
Snippet:
https://prnt.sc/hktg8s

Extract the archive to  the root of the child theme
http://i.prntscr.com/JXZqJAzdTt6-iz52lIFKFQ.png
[wc-vendors.zip](https://github.com/happivize/live/files/1542920/wc-vendors.zip)

**Comment by happivize** [comment]
I'm seeing this Item meta column on the export orders, can that be removed (easily)?
![image](https://user-images.githubusercontent.com/28787692/33798653-ab681896-dcea-11e7-9c15-8a3e31a62d62.png)

**Comment by shpp-shablyuk** [comment]
Done.
Changes in this snippet https://prnt.sc/hln4cx

**Comment by happivize** [comment]
I added that snippet to live and it did not change anything, even with Ctrl F5

![image](https://user-images.githubusercontent.com/28787692/33963955-d0f1c1c4-e024-11e7-9d3a-c3e6a68bd836.png)

![image](https://user-images.githubusercontent.com/28787692/33964072-3688b0d8-e025-11e7-91e8-005576d5843c.png)

![image](https://user-images.githubusercontent.com/28787692/33964090-48cc8e72-e025-11e7-809a-8fbc958784ed.png)

**Comment by shpp-shablyuk** [comment]
Did you do it https://prnt.sc/hnrp6a

**Comment by happivize** [comment]
No, I did not go back to see if you had given me other instructions
previously. Just saw that you said snippet.

It's probably best to wait for me to test it on dev and okay it before
giving me instructions on how to add to live, so there is no confusion with
what might have been written previously before it was completely fixed.

I have now done this extra step and it is working.

Thanks.
