### ISSUE TITLE
WC Vendor: Login for Vendor

### ISSUE THREAD

**Issue by happivize** [happivize/live#9]
Right now there isn't a good way for someone to go to login as a vendor. They have to login into my-account and then paste in https://happivize.com/vendor_dashboard.

Can you make Vendor Dashboard a box/menu here so they can easily navigate to it?

![image](https://user-images.githubusercontent.com/28787692/33734291-10a1ee22-db5a-11e7-983b-62307405ed6a.png)

**Comment by shpp-shablyuk** [comment]
Done

**Comment by happivize** [comment]
Thanks, looks good. Please provide details on how to move it to live

**Comment by shpp-shablyuk** [comment]
https://prnt.sc/hkte50

**Comment by happivize** [comment]
This worked, closed
